name: SpeedrunContest
main: fr.nebulo9.speedruncontest.SCPlugin
author: Nebulo9
version: 1.5b
description: This plugin provides a mean to play a Speedrun contest with your friends.
api-version: 1.16 #1.16.*

commands:
   runner:
      permission: src.runner
      description: Join or leave the runners list.
      usage: "Usage: /runner"
   runners:
      permission: src.runner
      description: Displays the current list of the runners
      usage: "Usage: /runners"
   game:
      permission: src.game
      description: Start, pause or stop a game.
      usage: "Usage: /game [start|stop|pause]"
   timer:
      permission: src.admin
      description: Pause, resume, stop and get the timer.
      usage: "Usage: /timer [get|pause|resume|stop]"

permissions:
   src.runner:
      default: true
      description: Grant access to /runner and /runners commands.
   src.game:
      default: op
      description: Grant access to /gamestart and /gamestop commands.
   src.admin:
      default: op
      description: Grant access to /gettime command.
      
   src.*:
      default: op
      description: Grant access to all commands of the plugin.
      children:
         src.runner: true
         src.game: true
         src.admin: true